#!/bin/bash
#
# Script to make a release tarbal

PRGNAME=$(basename $0)
DESTDIR=$(pwd)
#DESTDIR="/var/tmp"

CALLFLOW_VERSION=$(grep "readonly VersionSVN=" callflow | cut -d\" -f2 |
  awk '{split($4, A, "-"); print A[1] A[2] A[3] "-" $3}')

#CALLFLOW_VERSION=$(cat callflow.version)

# Only include files that are known, any other file is to be ignored
FILES="AUTHORS
CMakeLists.txt
callflow
conf/CMakeLists.txt
conf/callflow.conf
css/CMakeLists.txt
css/callflow.css
INSTALL
images/CMakeLists.txt
images/frame_bottom.png
images/frame_dynamic.png
images/frameless.png
images/frame_right.png
images/index.tpl
js/CMakeLists.txt
js/callflow.js
js/overlib.js
LICENSE
man/CMakeLists.txt
man/callflow.1
README
scripts/CMakeLists.txt
scripts/broadworks-parser.sh
scripts/callflow.awk
scripts/list-nodes.awk
scripts/long2html.awk
scripts/makevars.awk
scripts/marksession.awk
scripts/pcap-parser.sh
scripts/prunenodes.awk
scripts/removedups.sh"

# Verify location
FILE=$(echo "$FILES" | head -1)
[[ ! -f "$FILE" ]] && {
  ( echo "$PRGNAME: $FILE not found"
    echo "  might be in the wrong location"
  ) >&2
  exit 1
}

TMPDIR=/tmp/$PRGNAME.$$
mkdir -p $TMPDIR/callflow-$CALLFLOW_VERSION
tar cf - $FILES | (cd $TMPDIR/callflow-$CALLFLOW_VERSION; tar xf - )

sed -i "s/\(PRGVRSN\)=.*/\1=$CALLFLOW_VERSION/" $TMPDIR/callflow-$CALLFLOW_VERSION/callflow

TARBAL=$DESTDIR/callflow-$CALLFLOW_VERSION.tar.bz2
( cd $TMPDIR; tar cjf $TARBAL callflow-$CALLFLOW_VERSION)
rm -rf "${TMPDIR:xxxxx}"

if [[ -f $TARBAL ]]; then
  echo "$PRGNAME: tarbal stored at $TARBAL"
else
  echo "$PRGNAME: tarbal $TARBAL not found,"
  echo "  something went awfully wrong!"
fi

