/* please do not put anything before this comment */
/* the header of this file is automatically generated by callflow.sh and makevars.awk*/

/* This closing } is needed to finish off { generated in makevars.awk */
}

{ 
   l1 = sprintf("%s:%s", $2,$3);
   l2 = sprintf("%s:%s", $5,$6);
   
   for (i=0; i<numHosts; i++) {
	  if(l1 ~ hosts[i]) {
		 printf("%s\n",hosts[i]);
	  }
		 
	  if(l2 ~ hosts[i]) {
		 printf("%s\n",hosts[i]);
	  }
   }
}
  

